version: "3"
services:
  rails_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: jeffs2kul
      MYSQL_DATABASE: experiment_development
      MYSQL_USER: rails_user
      MYSQL_PASSWORD: rails_password
    ports:
      - "3006:3006"
  react-client:
    build:
      context: ./react-client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
